apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: golang-1234
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: golang-1234 
  name: golang-1234
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: golang-1234
    weight: 100 
